# Pendulum selection
Pendulums:
  double: true
  single: false

# Physical parameters
Phys:
  l1: 1.0
  l2: 1.0
  m1: 1.0
  m2: 1.0
  g: 9.81

# Neural Network parameters

NeuralNetwork:
  SP_path: "models/SinglePendulum/SP_NN_model.pt"
  DP_path: "models/DoublePendulum/DP_NN_model.pt"
  learning_rate: 1e-3
  EPOCHS: 1000
  BATCH_SIZE: 64
  hidden_size: 64

# Optimal Control Problem dimensions
OCP:
  horizon: 40
  dt: 0.05
  u_min: -5.0
  u_max: 5.0
  WithNN: true

  # Dimensions auto-set depending on pendulum type
  SP_state_dim: 2
  control_dim_single: 1

  state_dim_double: 4
  control_dim_double: 2

  # Cost function 
  q_target: 0




